### PR TITLE
Issue42489: Bug With experiment.save_batch

### PR DESCRIPTION
**Pull request by RosalineP**
#### Rationale
As described on the Issue, falsey values that are being passed within the form  `save_batch()` sends are blowing up when the server-side code attempts to pull JSONObjects out of null. Since defaults are applied when form attributes are not supplied, one solution is to strip out falsey values in the `to_json()` within the API.

I've verified locally that this works. 

I might also have ridiculously overengineered this through my desire to dynamically grab attribute items on `Run` to avoid a
`if self.file_path_root:
    data["filePathRoot"] = self.file_path_root` repeat x8 times type of situation. Let me know your thoughts on the approach here.

#### Related Pull Requests
* n/a

#### Changes
* Strip out falsey attribute values in `to_json()` of `Run`
* Update expected response upon hitting `save_batch()` within tests

### CODE REVIEW

**Comment by RosalineP** [comment]
Either PR would be appreciated depending on who gets the bandwidth, thank you! 👍

**Comment by RosalineP** [comment]
Guidance on bumping to version `2.1.0` and publishing would also be greatly appreciated!

**Comment by RosalineP** [comment]
Oh my gosh, saw a cleaner solution after PR that just uses a list comprehension. I think I prefer fix version 2 in 
fbf7038, but open to thoughts.

**Review by labkey-alan — APPROVED** [review]
Looks good. As discussed bump the version to 2.0.1 and update release notes before merging and I'll cut the new release.

**Pull request merged**
